<a href="https://colab.research.google.com/github/AAAilurus/Learnings/blob/main/Pytorch_full_cFundamentalsipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)



2.6.0+cu124


In [33]:
import torch
scalar = torch.tensor(7)
scalar.ndim
scalar.item()
vector = torch.tensor([7,7])
vector.shape
vector.ndim


1

In [34]:
import torch
matrix= torch.tensor([[7,8],[9,10]])
matrix.ndim
matrix[0]
matrix.shape

torch.Size([2, 2])

In [35]:
import torch
tensor= torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor.ndim
tensor.shape
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [36]:
import torch
random_tensor= torch.rand(3,4)
random_tensor.ndim


2

In [37]:
import torch
random_image_size_tensor= torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [38]:
import torch
zeros= torch.zeros(3,4)
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
import torch
ones= torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
import torch
a= torch.arange(start= 1, end=11, step = 1)
a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
import torch
b= torch.zeros_like(a)
b

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
import torch
float = torch.tensor([3.0, 6.0, 9.0], dtype= None, device = None, requires_grad= False )
float.dtype

torch.float32

In [43]:
import torch
float_16= float.type(torch.half)
float_32= float.type(torch.double)
float_16*float_32

tensor([ 9., 36., 81.], dtype=torch.float64)

In [44]:
import torch
tensor= torch.tensor([1,2,3])
print(f"Tensor addition",tensor+10)
print(tensor*10)
print(tensor-10)
print(tensor/10)

print(tensor.mul(10))



Tensor addition tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])
tensor([10, 20, 30])


In [45]:
import torch
tensor = torch.tensor([1,2,3])
print("Element wise multiplication",tensor*tensor)
print("Matrix multiplication", tensor@tensor)

Element wise multiplication tensor([1, 4, 9])
Matrix multiplication tensor(14)


In [46]:
import torch
tensor_A= torch.tensor([[1,2],[3,4],[5,6]])
tensor_B= torch.tensor([[7,10],[8,11],[9,12]])
torch.mm(tensor_A, tensor_B.T)# Transpose as same dimension is not for matmul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [47]:
import torch
x= torch.arange(start= 0,end= 100,step=10)
print(x)
print(x.min())
print(x.max())
print(torch.mean(x.type(torch.float32)))
print(x.sum())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0)
tensor(90)
tensor(45.)
tensor(450)


In [48]:
import torch
x= torch.arange(start=0, end=100, step=10)
print(x.argmin())
print(x.argmax())

tensor(0)
tensor(9)


In [49]:
import torch
x= torch.arange(1,9.)
print(x)
print(x.reshape(4,2))
z= x.view(1,8)
print(z, z.shape)
z[:,0]=5
z,x
x_stacked= torch.stack([x,x,x,x], dim=1)
print(x_stacked)
x_squeezed= x.reshape(1,8)
x_squeezed.squeeze()
x_unsqueezed= x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed)
X_original= torch.rand(size=(224,224,3))
x_permuted= X_original.permute(2,0,1)
print(x_permuted.shape)


tensor([1., 2., 3., 4., 5., 6., 7., 8.])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]) torch.Size([1, 8])
tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.]])
tensor([[[5., 2., 3., 4., 5., 6., 7., 8.]]])
torch.Size([3, 224, 224])


In [50]:
import torch
import numpy as np
array= np.arange(1.0,8.0)
tensor= torch.from_numpy(array)
array = array+1
array, tensor


(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [51]:
tensor= torch.ones(7)
numpy_tensor= tensor.numpy()

tensor = tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [52]:
import torch
random_tensor_A= torch.rand(3,4)
random_tensor_B= torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)


tensor([[0.3588, 0.9211, 0.8627, 0.8223],
        [0.5248, 0.5881, 0.2746, 0.3791],
        [0.2975, 0.6450, 0.0163, 0.9160]])
tensor([[0.5888, 0.8403, 0.4761, 0.7140],
        [0.4644, 0.6362, 0.8892, 0.1317],
        [0.7164, 0.2706, 0.6560, 0.6614]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [53]:
import torch
random_seed= 42
torch.manual_seed(random_seed)
random_tensor_c= torch.rand(3,4)
torch.manual_seed(random_seed)
random_tensor_d= torch.rand(3,4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [10]:
!nvidia-smi
import torch
#torch.cuda.is_available()
device= "cuda" if torch.cuda.is_available() else "cpu"
#device
tensor= torch.tensor([1,2,3])
tensor_on_gpu= tensor.to(device)
b=tensor_on_gpu.cpu().numpy()
b

Mon Aug 18 14:55:00 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   51C    P0             26W /   70W |     104MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

array([1, 2, 3])